import '../../domain/model/entities/maya_user_entities.dart';
import '../../domain/model/interfaces/seeder.dart';

/// A class responsible for seeding a list of sample user data.
/// 
/// The [UserSeeder] class implements the [Seeder] interface and generates a list of 
/// [MayaUserEntities] instances. This list can be used for populating the database or 
/// for testing purposes with pre-defined user data.
class UserSeeder extends Seeder {
  /// A private list that holds the sample user data.
  List<MayaUserEntities> _data = [];

  /// Asynchronously runs the seeding process to populate the list of users.
  ///
  /// This method creates multiple instances of [MayaUserEntities] with sample data for
  /// the fields: [username], [password], and [balance]. The sample users are added to the 
  /// internal [_data] list.
  ///
  /// Each user has a unique username, a randomly generated strong password, and a balance field
  /// that ranges from 50,000 to 100,000.
  @override
  Future<void> run() async {
    // Populate the _data list with sample user data
    _data = [
      MayaUserEntities(
          username: 'testaccount1',
          password: 'P@ssw0rd123!',
          balance: 50000),
      MayaUserEntities(
          username: 'testaccount2',
          password: 'Str0ngP@ssw0rd!',
          balance: 60000),
      MayaUserEntities(
          username: 'testaccount3',
          password: 'S3cure@P@ss2023',
          balance: 70000),
      MayaUserEntities(
          username: 'testaccount4',
          password: 'P@ssw0rd456!',
          balance: 80000),
      MayaUserEntities(
          username: 'testaccount5',
          password: 'Qwerty@123#',
          balance: 90000),
      MayaUserEntities(
          username: 'testaccount6',
          password: 'Str0ng!Passw0rd',
          balance: 100000),
      MayaUserEntities(
          username: 'testaccount7',
          password: 'Maya@2023#Strong',
          balance: 100000),
      MayaUserEntities(
          username: 'testaccount8',
          password: 'Secure!P@ssw0rd123',
          balance: 100000),
      MayaUserEntities(
          username: 'testaccount9',
          password: 'Test@456P@ss!',
          balance: 100000),
      MayaUserEntities(
          username: 'testaccount10',
          password: 'P@ssw0rd789#',
          balance: 100000),
    ];
  }

  /// Returns the list of sample users generated by the [run] method.
  /// 
  /// This getter allows access to the list of users for further operations (e.g., database insertion).
  List<MayaUserEntities> get data => _data;
}